### ISSUE TITLE
数据链接失效

### ISSUE THREAD

**Issue by wanheng99** [EnernityTwinkle/KBQA-QueryGraphSelection#1]
我们已训练的模型和部分中间结果,包含中文和英文数据集内容

**Comment by wanheng99** [comment]
> 
这个链接失效了，可以重新分享一下吗

**Comment by cytan17726** [comment]
你好，百度网盘已弃用，可至[Google Drive](https://drive.google.com/drive/folders/18G4h41Pvh7rdZ2wBAKxVw079Fnybv1-T?usp=sharing)获取
